spring:
  application:
    name: gatewayserver
  cloud:
    config:
      # Profile field can be changed based on person
      profile: local-ibrahim
  config:
    import: "optional:configserver:${configUrl}/"


configUrl: http://localhost:8079